version: "3.8"
services:
  seasonalbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seasonalbot
    init: true

    restart: always

    environment:
      - SEASONALBOT_TOKEN=yourtokenhere
      - SEASONALBOT_DEBUG=true
      - AOC_ROLE_ID=651730380898041862
      - AOC_CHANNEL_ID=651732924391227392
    # - SEASONALBOT_GUILD=
    # - SEASONALBOT_ADMIN_ROLE_ID=
    # - CHANNEL_ANNOUNCEMENTS=
    # - CHANNEL_DEVLOG=

    volumes:
      - /opt/pythondiscord/seasonalbot/log:/bot/bot/log
      - /opt/pythondiscord/seasonalbot/data:/bot/data
